# Numpy_2 : petits exercices 
Ce notebook a pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste d'exercices à faire, ne pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [2]:
np.__version__

'1.16.2'

In [3]:
np.version.version

'1.16.2'

#### Q3 : Créer un vecteur nul de taille 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#Pour un tableau: np.zeros((size))
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.full((2,10),5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 5ème place (index 4) du vecteur

In [8]:
v=np.zeros(10)
v[4]=1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [9]:
Z=np.random.randint(10,50,size=(40))
Z

array([42, 10, 24, 14, 29, 49, 48, 29, 22, 35, 41, 15, 42, 36, 47, 32, 46,
       25, 25, 31, 11, 12, 25, 46, 19, 41, 42, 33, 29, 29, 17, 10, 30, 42,
       27, 41, 43, 23, 19, 28])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [10]:
Z[::-1]

array([28, 19, 23, 43, 41, 27, 42, 30, 10, 17, 29, 29, 33, 42, 41, 19, 46,
       25, 12, 11, 31, 25, 25, 46, 32, 47, 36, 42, 15, 41, 35, 22, 29, 48,
       49, 29, 14, 24, 10, 42])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [11]:
M3=np.random.randint(8,size=(3,3))
M3

array([[0, 0, 6],
       [6, 0, 2],
       [4, 2, 0]])

#### Q8 : Créer une matrice identié 3x3 

In [12]:
I3=np.eye(3)
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [13]:
M3D=np.random.randint(100,size=(3,3,3))
M3D

array([[[62,  0, 64],
        [75, 57, 96],
        [62, 12,  3]],

       [[ 6, 99, 37],
        [ 9,  7, 75],
        [62, 78, 43]],

       [[79, 24, 40],
        [18, 55, 70],
        [86, 37, 75]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum 

In [14]:
M10=np.random.randint(100,size=(10,10))
M10

array([[19, 89,  4, 61, 18, 96,  8, 85, 48, 65],
       [60, 91,  4, 98, 60, 69,  2, 24, 37, 39],
       [64, 31, 19, 80,  2, 73, 78, 38, 51, 21],
       [ 9, 29, 53,  2, 85, 56, 41, 10, 84, 49],
       [ 6, 57, 99, 84, 19, 47, 94, 51, 84, 37],
       [ 5, 61, 28,  5, 81, 68, 68,  1, 89, 82],
       [37, 71, 62, 77, 30, 47, 93, 88, 59, 86],
       [15, 80, 21, 22, 87, 44, 52, 57, 36, 65],
       [81, 45,  9,  1, 93, 91, 12, 50, 22, 93],
       [10, 12, 72,  4, 24, 85, 15, 18, 20, 82]])

In [16]:
np.min(M10)

1

In [17]:
np.max(M10)

99

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [18]:
M5=np.random.randint(100,size=(5,5))
print(M5)
print()
M5[1][0]=1
M5[2][1]=2
M5[3][2]=3
M5[4][3]=4
print(M5)

[[54 74 20 33  9]
 [34 78 78 33 81]
 [76 42 35  3 29]
 [80 87  0 43 43]
 [94 23 65 41 16]]

[[54 74 20 33  9]
 [ 1 78 78 33 81]
 [76  2 35  3 29]
 [80 87  3 43 43]
 [94 23 65  4 16]]


**Obtenir une mactrice triangulaire:**

In [19]:
M5=np.random.randint(100,size=(5,5))
print(M5)
print()
np.tril(M5,0)

[[35 73 73  3 44]
 [10 11 89 35 35]
 [71 23 27 41 98]
 [ 2 56 85 28 38]
 [80 68 37 67 83]]



array([[35,  0,  0,  0,  0],
       [10, 11,  0,  0,  0],
       [71, 23, 27,  0,  0],
       [ 2, 56, 85, 28,  0],
       [80, 68, 37, 67, 83]])

In [20]:
M15=np.random.randint(1,5,size=(5,5))
print(M15)
print()
np.tril(M15,0)

[[3 4 4 2 4]
 [2 4 2 3 3]
 [3 1 2 2 3]
 [1 3 2 2 3]
 [1 1 4 1 2]]



array([[3, 0, 0, 0, 0],
       [2, 4, 0, 0, 0],
       [3, 1, 2, 0, 0],
       [1, 3, 2, 2, 0],
       [1, 1, 4, 1, 2]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [21]:
from random import randint

L=[randint(0,31) for i in range(5)]
print(L)
sum(L)

[8, 27, 21, 24, 13]


93

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [22]:
L1=[randint(0,31) for i in range(5)]
print(L1)
np.mean(L1)

[7, 6, 13, 19, 31]


15.2

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante : l = [0,1,2,3,4,5,6,7]

In [23]:
l = [0,1,2,3,4,5,6,7]
def taille(l):
    return l[-1]+1
taille(l)

8

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [24]:
T=np.random.rand(1,10)
T

array([[0.4983944 , 0.0253756 , 0.72967871, 0.59615345, 0.34804863,
        0.64472737, 0.14271143, 0.96594203, 0.38371676, 0.98783877]])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [25]:
A=np.random.randint(10,size=(5))
B=np.random.randint(10,size=(5))
print(A)
print(B)
print(A==B)                    #compare les termes 1 à 1 dans A et B
print(A.size == B.size) 
print(A.shape == B.shape)

[2 6 6 1 2]
[9 7 9 4 2]
[False False False False  True]
True
True


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [23]:
#Crée un tableau 1x10 en floats entre 0 et 1:
t_f=np.random.rand(1,10)
print(t_f)
t_f.dtype

[[0.42674219 0.39958976 0.68865492 0.13789982 0.92676526 0.98677806
  0.81768791 0.42387838 0.54465331 0.7212645 ]]


dtype('float64')

In [24]:
#Crée un tableau 1x10 en floats entre 0 et 1 arrondi aux décimales souhaitées:
tf=np.around(np.random.rand(1,10), decimals=3)
print(tf)
tf.dtype

[[0.898 0.962 0.219 0.621 0.271 0.345 0.1   0.681 0.645 0.843]]


dtype('float64')

In [25]:
#Autre création de tableau 1x10 en floats (loi normale):
t_ff=np.random.randn(1,10)
print(t_ff)
t_ff.dtype

[[-0.30522958  0.69856875 -0.63709424  0.59337264  0.64602144  0.14248753
  -1.24903173  2.94323716  1.88489256  0.85523732]]


dtype('float64')

In [26]:
#Convertit le tableau de floats en integers avec .astype(int):
ti=t_f.astype(int)
print(ti)
ti.dtype

[[0 0 0 0 0 0 0 0 0 0]]


dtype('int32')

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par l'écart type de X

In [27]:
Mat5=np.random.randint(20, size=(5,5))
Mat5

array([[ 8,  3,  6,  5,  9],
       [ 8,  4, 13, 12, 15],
       [15,  7,  9, 19,  3],
       [ 7,  5,  7, 11,  2],
       [19,  3,  1, 10, 14]])

In [28]:
#Moyenne de la matrice:
np.mean(Mat5)

8.6

In [29]:
#Ecart type de la matrice:
np.std(Mat5)

4.995998398718718

In [30]:
#Normalisation de la matrice:
(Mat5 - (np.mean(Mat5))) / np.std(Mat5)

array([[-0.12009612, -1.12089708, -0.5204165 , -0.72057669,  0.08006408],
       [-0.12009612, -0.92073688,  0.88070485,  0.68054465,  1.28102523],
       [ 1.28102523, -0.32025631,  0.08006408,  2.081666  , -1.12089708],
       [-0.32025631, -0.72057669, -0.32025631,  0.48038446, -1.32105727],
       [ 2.081666  , -1.12089708, -1.52121746,  0.28022427,  1.08086504]])

#### Q19 : Créer une matrice random 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [31]:
Mat2=np.random.randint(30, size=(2,2))
Mat2

array([[15, 22],
       [10,  8]])

In [32]:
Mat2.T

array([[15, 10],
       [22,  8]])

ou 2ème méthode:

In [33]:
Mat3=np.random.randint(30, size=(2,2))
Mat3

array([[ 5, 11],
       [19, 19]])

In [34]:
np.transpose(Mat3)

array([[ 5, 19],
       [11, 19]])

**Modification d'un tableau:**

In [35]:
T=np.random.randint(10, size=(5,5))
T

array([[4, 3, 0, 8, 2],
       [5, 2, 8, 4, 7],
       [3, 8, 4, 0, 7],
       [4, 8, 2, 4, 3],
       [7, 0, 4, 0, 8]])

In [36]:
#Mélange les lignes mais conserve T:
np.random.permutation(T)

array([[7, 0, 4, 0, 8],
       [4, 8, 2, 4, 3],
       [3, 8, 4, 0, 7],
       [4, 3, 0, 8, 2],
       [5, 2, 8, 4, 7]])

In [37]:
T

array([[4, 3, 0, 8, 2],
       [5, 2, 8, 4, 7],
       [3, 8, 4, 0, 7],
       [4, 8, 2, 4, 3],
       [7, 0, 4, 0, 8]])

In [38]:
#Modifie T en mélangeant les lignes. On ne pourra plus appelé le tableau dans l'ordre d'origine:
np.random.shuffle(T)
T

array([[4, 8, 2, 4, 3],
       [3, 8, 4, 0, 7],
       [7, 0, 4, 0, 8],
       [4, 3, 0, 8, 2],
       [5, 2, 8, 4, 7]])

#### Q20 : Écrire un script qui remplace un élément au hasard dans une matrice de dimension NxN

In [39]:
Mat5=np.random.randint(20, size=(5,5))
Mat5

array([[14, 12, 11, 10, 12],
       [ 1,  7,  3, 13,  6],
       [16,  0, 16,  8, 12],
       [15, 11, 13,  1, 10],
       [ 1,  3,  9,  2,  9]])

In [40]:
len(Mat5)                   #: donne le nombre de lignes (n ds n,p)

5

In [41]:
#choisit une ligne au hasard et un nombre au hasard dans cette ligne:
#M[.][.] ou M[.,.]. Il faut privilégier la 2ème solution.

ch=Mat5[np.random.randint(len(Mat5))][np.random.randint(len(Mat5))]
ch

12

In [42]:
#Remplace la valeur choisie par 1:
Mat5[Mat5==ch]=1                #remplace la valeur où la [matrice == ch] par la valeur 1
Mat5

array([[14,  1, 11, 10,  1],
       [ 1,  7,  3, 13,  6],
       [16,  0, 16,  8,  1],
       [15, 11, 13,  1, 10],
       [ 1,  3,  9,  2,  9]])

**Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)**

In [43]:
D=np.random.randint(20,size=(5,5,3))
E=np.random.randint(20,size=(5,5))
print(D)
print(E)

[[[16  3  7]
  [12 11 13]
  [12 11 18]
  [12  3  0]
  [ 7 10  0]]

 [[18 18 13]
  [ 5  5 18]
  [ 0 11 17]
  [ 3 19  6]
  [12 10 18]]

 [[ 8  5 13]
  [17 10 15]
  [ 9  3  7]
  [12  9  0]
  [16 18 10]]

 [[10 12  5]
  [ 0 16 19]
  [ 4  3 13]
  [ 7 19  9]
  [19 13  4]]

 [[ 8 17  4]
  [10 11  6]
  [ 4  1  9]
  [ 8 17 13]
  [15  8 19]]]
[[10  3  8  2 16]
 [15 10  5  9  4]
 [13 11 14 18 17]
 [ 7  4  3  6 10]
 [ 2  4  0  2 19]]


In [44]:
E @ D  

array([[[ 428,  317,  253],
        [ 556,  277,  325],
        [ 843,  538,  486],
        [ 338,  216,  155],
        [ 237,  246,   66]],

       [[ 393,  481,  620],
        [ 395,  586,  586],
        [ 547,  955, 1019],
        [ 284,  393,  430],
        [ 290,  284,  452]],

       [[ 483,  410,  391],
        [ 507,  343,  420],
        [ 905,  685,  602],
        [ 383,  318,  272],
        [ 412,  410,  276]],

       [[ 450,  438,  293],
        [ 309,  578,  427],
        [ 635,  937,  686],
        [ 314,  401,  244],
        [ 395,  373,  180]],

       [[ 398,  373,  460],
        [ 372,  555,  358],
        [ 669,  798,  801],
        [ 306,  348,  347],
        [ 357,  264,  419]]])

In [45]:
np.tensordot(E,D)

array([2399, 2253, 2104])

In [46]:
np.tensordot(E,D,1)

array([[[ 426,  420,  287],
        [ 431,  413,  438],
        [ 264,  189,  457],
        [ 367,  469,  244],
        [ 512,  428,  446]],

       [[ 582,  426,  361],
        [ 355,  453,  645],
        [ 277,  321,  628],
        [ 365,  519,  193],
        [ 536,  489,  342]],

       [[ 834,  812,  574],
        [ 619,  813, 1021],
        [ 422,  377,  906],
        [ 619, 1005,  449],
        [1044,  862,  733]],

       [[ 348,  350,  210],
        [ 255,  333,  382],
        [ 175,  158,  383],
        [ 254,  408,  208],
        [ 409,  322,  316]],

       [[ 276,  425,  152],
        [ 234,  283,  250],
        [ 108,   91,  301],
        [ 202,  443,  289],
        [ 385,  238,  441]]])

In [47]:
A=np.array([1,2,3,4])
B=np.array([[4,6,7,8],[9,10,11,12]])
print (A*B)
print()
print(B @ A)

[[ 4 12 21 32]
 [ 9 20 33 48]]

[ 69 110]
