# Numpy_1 

In [1]:
import numpy as np

## Quelques fonctions utiles

On a créé un tableau 2D contenant des valeurs aléatoires. 

In [2]:
#t=np.ramdom.randn(shape)           : créer un tableau de floats aléatoires (loi normale)
#t=np.random.rand(shape)            : créer un tableau de floats aléatoires entre 0 et 1 exclu
#t=np.linspace(a,b,c)               : créer un tableau de floats aléatoires régulièrement répartis
#                                     entre a et b, de taille c

#t=np.random.randint(a, size=(b, c)): créer un tableau d'entiers aléatoires de 0 à a
#                                     (b, c) = shape

#t=np.arange(a)                     : créer un tableau d'entiers de 0 à a (avec un pas de 1)
#t=np.arange(a,b)                   : créer un tableau d'entiers de a à b (avec un pas de 1)
#t=np.arange(35).reshape(5,7)       : créer un tableau d'entier de 0 à 34
#                                   : les attributs doivent être des multiples de 35 sinon errors

#t=np.array([a,b,c,d])              : créer un tableau directement avec des valeurs
#                                   : depuis Python directement : ndarray([a,b,c,d])


rdm_mat = np.random.randn(20, 20)
rdm_mat

array([[-4.27497643e-01,  3.51515583e-01, -5.94954133e-01,
         1.18701989e+00, -1.58667308e+00, -1.50892811e-01,
         1.03572729e+00,  3.84570131e-01, -8.87031272e-01,
         1.21957853e-01,  5.12039963e-01, -5.39523830e-01,
        -1.16605733e-01,  2.14686938e+00, -1.53192056e+00,
         1.73020126e-01,  5.98001983e-01,  2.56517466e-02,
        -1.31378773e+00, -1.31625386e+00],
       [-4.71726077e-01,  2.54174679e-01,  1.65378334e+00,
        -5.19891319e-01,  1.40124719e+00, -9.24285407e-01,
         2.25542727e+00,  3.23993238e-01,  1.16010361e+00,
         7.87179698e-01, -2.27910130e-01,  1.29472193e-01,
        -6.37528462e-01, -1.15064901e-02, -5.18310928e-01,
         2.14156726e-01, -3.76854527e-01, -5.42635613e-01,
        -4.76452598e-01,  1.13459624e+00],
       [ 4.98981805e-01,  5.75935425e-01, -1.30036898e-01,
        -7.26259810e-01, -2.19280937e-01, -7.90115232e-01,
         8.65529751e-01, -2.23705558e+00, -6.14736510e-01,
         6.63666829e-01, -6.1

Donner le type de la variable rdm_mat

In [3]:
type(rdm_mat)

numpy.ndarray

Donner le type de données au sein de la variable rdm_mat

In [4]:
rdm_mat.dtype

dtype('float64')

Donner les caractéristiques du tableau:

In [5]:
#Donne la dimension du tableau:
rdm_mat.ndim

2

In [6]:
#Donne la forme du tableau (nombre de colonnes et de lignes):
rdm_mat.shape

(20, 20)

In [7]:
#Donne la taille (20x20) :
rdm_mat.size

400

Donner la somme des éléments de ce tableau 2D

In [8]:
np.sum(rdm_mat)

15.045203464238407

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [9]:
np.max(rdm_mat, axis=1) 

array([2.14686938, 2.25542727, 2.75123877, 2.55772566, 1.88263059,
       2.02240894, 2.62646186, 1.67183135, 1.77899356, 2.27005494,
       1.497744  , 2.17388562, 1.82130619, 1.57838858, 1.74155197,
       1.22338887, 2.25040161, 1.45939118, 2.29911586, 1.88901862])

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [10]:
np.max(rdm_mat, axis=0)

array([1.47036975, 1.94599345, 1.74155197, 1.82130619, 1.40124719,
       2.62646186, 2.25542727, 1.72225368, 1.57838858, 2.25040161,
       1.01897793, 2.27005494, 2.55772566, 2.14686938, 1.59522444,
       1.82749503, 0.82962504, 2.75123877, 1.77899356, 1.23253168])

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

In [11]:
ma_mat=np.random.randint(20, size=(5, 3))
ma_mat

array([[10, 18,  3],
       [ 6, 12, 13],
       [ 6, 13, 18],
       [15,  0, 14],
       [10,  6, 19]])

In [12]:
def max_tab(matr):
    t=[]
    for i in range(len(matr)):          # i = ligne
        t.append(np.max(matr[i]))       # max pour chaque ligne
    return t

max_tab(ma_mat)

[18, 13, 18, 15, 19]

On crée un vecteur aléatoire

In [13]:
v=np.random.randint(20, size=(10))
v

array([ 1,  1, 17,  0, 11,  1, 16, 16, 19,  6])

In [14]:
#crée un tableau de a à b exclus:
w=np.arange(0,10)
w

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#crée un tableau de a à b avec un pas de c:
p=np.arange(0,20,5)
p

array([ 0,  5, 10, 15])

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [16]:
print(v)
#Donne l'index (la position) où se trouve la valeur maximale du tableau:
np.argmax(v)

[ 1  1 17  0 11  1 16 16 19  6]


8

Afficher cette valeur 

In [17]:
#Donne la valeur maximale comprise dans la liste:
np.max(v)

19

Convertir le vecteur en un tableau 10, 10

In [18]:
v.reshape(2,5)                   #reshape fonctionne car j'ai demandé une taille qui correspond
                                 #    au nombre de données que j'avais à l'origine : 10 valeurs
                                 #ne fonctionne pas pour faire un tableau 10,10.

array([[ 1,  1, 17,  0, 11],
       [ 1, 16, 16, 19,  6]])

In [19]:
v=np.random.randint(20, size=(10))
v.resize(10,10)                   #créer mon tableau comme souhaité en le remplissant de
v                                 #                        0 pour les valeurs manquantes

array([[ 8,  2,  4, 12, 18, 15,  5, 19, 15,  6],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [20]:
np.mean(v,axis=1)

array([10.4,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ])

In [21]:
#Moyennne du tableau:
np.mean(v)

1.04

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

In [22]:
tab=np.mean(v, axis=0)
tab

array([0.8, 0.2, 0.4, 1.2, 1.8, 1.5, 0.5, 1.9, 1.5, 0.6])

In [23]:
#Avec une boucle:
for i in range(len(v)):
    m=np.sum(v, axis=0)/len(v)
m

array([0.8, 0.2, 0.4, 1.2, 1.8, 1.5, 0.5, 1.9, 1.5, 0.6])

Calculer la somme de chaque colonne (sans boucles)

In [24]:
np.sum(v, axis=0)

array([ 8,  2,  4, 12, 18, 15,  5, 19, 15,  6])

Calculer la somme pour chaque ligne (sans boucles)

In [25]:
np.sum(v, axis=1)

array([104,   0,   0,   0,   0,   0,   0,   0,   0,   0])

 ## Opérations sur les tableaux:

In [26]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])

A+B         # additionne chaque élément correspondant du tableau 1 et du tableau 2

array([ 7,  9, 11, 13, 15])

In [27]:
A + 30      # additionne 30 à chaque élément du tableau

array([31, 32, 33, 34, 35])

In [28]:
A * B       # multpilie chaque élément de A par chaque élément de B

array([ 6, 14, 24, 36, 50])

In [29]:
A @ B       # dot product / produit scalaire de A et B = multiplication des matrices
            #                       en elle-mm, pas de leurs éléments indépendemment

130

In [30]:
z=np.array([1,2,3,4,5])
z

array([1, 2, 3, 4, 5])

In [31]:
z[:-2]

array([1, 2, 3])

In [32]:
z[2:-1]

array([3, 4])

In [33]:
#reverse tableau avec un pas de -1:
z[::-1]

array([5, 4, 3, 2, 1])

Comparateurs:

In [34]:
#pose une question booléenne
#is i>3 in longueur de z:
z>3

array([False, False, False,  True,  True])

In [35]:
#montre uniquement les valeurs supérieurs à 3 ds le tableau z:
z[z>3]

array([4, 5])

In [ ]:
z.       #+tab : donne ttes les fonctions que l'on peut faire ac z.
?z       #donne la doc sur cette variable
?z.shape #idem

Concaténer:

In [37]:
#Tableaux de 1 dimension:
x=np.array([1,2,3])
y=np.array([4,5,6])
c=np.concatenate([x,y])
c

array([1, 2, 3, 4, 5, 6])

In [38]:
#Tableaux de 2 dimensions (ou plus):
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
c=np.concatenate([x,y])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
#Tableaux de 2 dimensions (ou plus):
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
c=np.concatenate([x,y],axis=1)     #concaténation sur les lignes
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])